version: "3"
services:
  php:
    build: ./docker/php
    depends_on:
      - db
    volumes:
      - ./sylius:/var/www/html
    ports:
      - 80
    networks:
      - default
      - traefik
    labels:
      traefik.docker.network: "traefik"
      traefik.frontend.rule: "Host:sylius.test"

  composer:
    image: composer
    depends_on:
      - db
    volumes:
      - ./sylius:/app
    working_dir: /app
    entrypoint: composer

  db:
    image: mariadb:10.2
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sylius
      MYSQL_USER: sylius
      MYSQL_PASSWORD: sylius

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 80
    networks:
      - default
      - traefik
    labels:
      traefik.docker.network: "traefik"
      traefik.frontend.rule: "Host:pma.sylius.test"

volumes:
  db-data:
    driver: local

networks:
  traefik:
    external: true
