name: Node CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Slack notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Github Gatsbylius # Optional.
        SLACK_CHANNEL: gatsbylius # Optional.
      uses: Ilshidur/action-slack@master
      with:
        args: 'A new commit has been pushed starting build.'

    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    
    - name: Slack notification
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Github Gatsbylius # Optional.
        SLACK_CHANNEL: gatsbylius # Optional.
      uses: Ilshidur/action-slack@master
      with:
        args: 'Error on commit build'
        
    - name: Slack notification
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Github Gatsbylius # Optional.
        SLACK_CHANNEL: gatsbylius # Optional.
      uses: Ilshidur/action-slack@master
      with:
        args: 'Commit build successfully'

   
