name: Node CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./demo
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github Gatsbylius # Optional.
          SLACK_CHANNEL: gatsbylius # Optional.
        uses: Ilshidur/action-slack@master
        with:
          args: "Modifications has been pushed on master, starting build..."
      - name: set environment variables
        working-directory: ${{env.working-directory}}
        uses: allenevans/set-env@v1.0.0
        with:
          GATSBY_SYLIUS_URL: ${{ secrets.SYLIUS_URL }}
      - name: npm install, build, and test
        working-directory: ${{env.working-directory}}
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: Slack notification
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github Gatsbylius # Optional.
          SLACK_CHANNEL: gatsbylius # Optional.
        uses: Ilshidur/action-slack@master
        with:
          args: "Error on master branch build"
      - name: Slack notification
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github Gatsbylius # Optional.
          SLACK_CHANNEL: gatsbylius # Optional.
        uses: Ilshidur/action-slack@master
        with:
          args: "Master build successfully, run deploy..."
      - name: deploy to server
        working-directory: ${{env.working-directory}}
        if: success()
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-e -c -r --delete"
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          FOLDER: "./public/"
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
